/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cn.ac.bmi.cloudphr.ckmirror;

import cn.ac.bmi.cloudphr.ckmirror.repository.ArchetypeInfoRepository;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.SQLException;

@SpringBootApplication
@Slf4j
public class App implements CommandLineRunner {
    @Autowired
    private DataSource dataSource;

    @Autowired
    private ArchetypeInfoRepository archetypeInfoRepository;

    public static void main(String[] args) throws Exception {
        SpringApplication.run(App.class, args);
    }

    @Override
    public void run(String... args) throws Exception {
        showConnection();
    }

    private void showConnection() throws SQLException {
        log.info(dataSource.toString());
        Connection conn = dataSource.getConnection();
        log.info(conn.toString());
        conn.close();
    }

    public void UpdateDatabase() {
        CKMHelper.parseCKMRepository();
        for (ArchetypeInfo info : CKMHelper.archetypeInfoList) {
            if (archetypeInfoRepository.findByArchetypeID(info.getArchetypeID()) == null) {
                // 插入这条原型信息
                // 下载相应的原型到相应的目录
            } else {
                if (!info.getUpdatedAt().equals(archetypeInfoRepository.findByArchetypeID(info.getArchetypeID()).getUpdatedAt())) {
                    // 下载相应的原型到相应的目录
                }
                // 更新表中的这条原型信息
            }
        }
    }
}
