FROM gradle:jdk8 as cache
RUN mkdir -p /home/gradle/cache
ENV GRADLE_USER_HOME /home/gradle/cache
COPY build.gradle /home/gradle/src/
WORKDIR /home/gradle/src
RUN gradle clean dependencies -i --stacktrace

FROM gradle:jdk8 AS builder
COPY --from=cache /home/gradle/cache /home/gradle/.gradle
COPY --chown=gradle:gradle . /home/gradle/src

# Add crontab file in the cron directory
#COPY --chown=gradle:gradle Crontabfile /etc/cron.d/hello-cron

WORKDIR /home/gradle/src
RUN gradle clean build
RUN mkdir  -p target
WORKDIR /home/gradle/src/target
RUN jar -xf ../build/libs/*.jar



FROM openjdk:8-jre-slim
COPY --from=builder /home/gradle/src/build/distributions/ckmirror.tar /app/
# COPY --chown=root:root Crontabfile /etc/cron.d/hello-cron
WORKDIR /app
RUN ls -al
RUN tar -xvf ckmirror.tar
WORKDIR /app/ckmirror

RUN sed -i 's/deb.debian.org/mirrors.aliyun.com/g' /etc/apt/sources.list
RUN apt-get update && apt-get install -y cron && apt-get install -y vim

# COPY --from=builder /etc/cron.d/hello-cron /etc/cron.d/hello-cron
# COPY --chown=root:crontab Crontabfile /var/spool/cron/crontabs/root
RUN touch /var/spool/cron/crontabs/root
RUN chmod 600 /var/spool/cron/crontabs/root
RUN echo "EDITOR=vi; EXPORT EDITOR" >> /root/.profile
RUN echo "*/1 * * * * date >> /var/log/cron.log\n" >> /var/spool/cron/crontabs/root
RUN echo "*/1 * * * * export JAVA_HOME=/usr/local/openjdk-8; /app/ckmirror/bin/ckmirror >> /var/log/cron.log\n" >> /var/spool/cron/crontabs/root
# RUN cat /var/spool/cron/crontabs/root
# Give execution rights on the cron job
#RUN chmod 0644 /etc/cron.d/hello-cron
# Create the log file to be able to run tail
RUN touch /var/log/cron.log
# 日志文件重定向到控制台
# RUN ln -sfT /dev/stdout "/var/log/cron.log"

#启动cron服务，会自动调度“/var/spool/cron/crontabs/root”运行
# RUN service cron start

CMD service cron start && tail -f /var/log/cron.log
